# Generated by Django 5.1.2 on 2024-10-24 13:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('IP', models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(64)])),
                ('username', models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256)], verbose_name='Nome de Usuário')),
                ('password', models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256)], verbose_name='Senha')),
                ('URL', models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(256)])),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
