# Generated by Django 5.2.1 on 2025-05-20 14:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('IP', models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(64)])),
                ('username', models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256)])),
                ('password', models.CharField(blank=True, max_length=256, null=True, validators=[django.core.validators.MaxLengthValidator(256)])),
                ('URL', models.CharField(max_length=256, validators=[django.core.validators.MaxLengthValidator(256)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
