notes: list[tuple[str, str]] = [
    ('wrk', 'Work'),
    ('std', 'Study'),
    ('cmt', 'Commitment'),
    ('fml', 'Family'),
    ('hlt', 'Health'),
    ('fin', 'Finance'),
    ('trv', 'Travel'),
    ('vol', 'Volunteer'),
    ('rel', 'Religious'),
    ('leg', 'Legal'),
]

cards_types: list[tuple[str, str]] = [
    ('deb', 'Debit'),
    ('cred', 'Credit'),
    ('pre', 'Prepaid'),
    ('co', 'Co-branded'),
]

banks: list[tuple[str, str]] = [
    ('abn-amro--', 'ABN Amro'),
    ('amp-ltd--', 'AMP Limited'),
    ('anz-new-zealand--', 'ANZ Bank New Zealand'),
    ('absabank-group--', 'Absa Bank Group'),
    ('access-bank-plc--', 'Access Bank Plc'),
    ('agricultural-bank-of-china--', 'Agricultural Bank of China'),
    ('ally-fin--', 'Ally Financial'),
    ('american-express-bank--', 'American Express National Bank'),
    ('attijariwafa-bank--', 'Attijariwafa Bank'),
    (
        'austr-and-new-zland-banking-gp--',
        'Australia and New Zealand Banking Group',
    ),
    ('axis-bank--', 'Axis Bank'),
    ('bnp-paribas--', 'BNP Paribas'),
    ('original--', 'Banco Original'),
    ('santander--', 'Banco Santander'),
    ('banco-do-brasil--', 'Banco do Brasil'),
    ('bangkok-bank--', 'Bangkok Bank'),
    ('bank-of-america--', 'Bank of America'),
    ('bank-of-china--', 'Bank of China'),
    ('bank-of-queensland--', 'Bank of Queensland'),
    ('banque-misr--', 'Banque Misr'),
    ('barclays--', 'Barclays'),
    ('bendigo-and-adelaide-bank--', 'Bendigo and Adelaide Bank'),
    ('bradesco--', 'Bradesco'),
    ('c6-bank--', 'C6 Bank'),
    ('caixa--', 'Caixa'),
    ('capital-one--', 'Capital One'),
    ('capitec-bank--', 'Capitec Bank'),
    ('china-construction-bank--', 'China Construction Bank'),
    ('citibank-australia--', 'Citibank Australia'),
    ('citigroup--', 'Citigroup'),
    ('citizens-bank--', 'Citizens Bank'),
    (
        'commercial-inter-bank-of-egypt--',
        'Commercial International Bank of Egypt',
    ),
    ('commerzbank--', 'Commerzbank'),
    ('commonwealth-bank--', 'Commonwealth Bank'),
    ('credit-suisse--', 'Credit Suisse'),
    ('credit-suisse-australia--', 'Credit Suisse Australia'),
    ('credit-agricole--', 'Crédit Agricole'),
    ('dbs-group-holdings--', 'DBS Group Holdings'),
    ('danske-bank--', 'Danske Bank'),
    ('deutsche-bank--', 'Deutsche Bank'),
    ('deutsche-bank-australia--', 'Deutsche Bank Australia'),
    ('ecobank-transnat-incorp--', 'Ecobank Transnational Incorporated'),
    ('fifth-third-bank--', 'Fifth Third Bank'),
    ('first-city-monument-bank--', 'First City Monument Bank'),
    ('firstrand-ltd--', 'FirstRand Limited'),
    ('goldman-sachs--', 'Goldman Sachs'),
    ('guaranty-trust-bank--', 'Guaranty Trust Bank'),
    ('hdfc-bank--', 'HDFC Bank'),
    ('hsbc--', 'HSBC'),
    ('icici-bank--', 'ICICI Bank'),
    ('ing-bank-australia--', 'ING Bank Australia'),
    ('ing-group--', 'ING Group'),
    (
        'industr-n-comme-bank-of-china--',
        'Industrial and Commercial Bank of China',
    ),
    ('intesa-sanpaolo--', 'Intesa Sanpaolo'),
    ('investec--', 'Investec'),
    ('itau--', 'Itaú'),
    ('jpmorgan-australia--', 'JPMorgan Australia'),
    ('jpmorgan-chase--', 'JPMorgan Chase'),
    ('kbc-fin-group--', 'KBC Financial Group'),
    ('kasikornbank--', 'Kasikornbank'),
    ('keycorp--', 'KeyCorp'),
    ('latitude-fin-servs--', 'Latitude Financial Services'),
    ('liberty-fin-group--', 'Liberty Financial Group'),
    ('lloyds-banking-group--', 'Lloyds Banking Group'),
    ('m-t-bank--', 'M&T Bank'),
    ('mmi-holdings--', 'MMI Holdings'),
    ('macquarie-group--', 'Macquarie Group'),
    ('maybank--', 'Malayan Banking Berhad (Maybank)'),
    ('mercadopago--', 'Mercado Pago'),
    ('mitsubishi-ufj-fin-group--', 'Mitsubishi UFJ Financial Group'),
    ('mizuho-fin-group--', 'Mizuho Financial Group'),
    ('morgan-stanley--', 'Morgan Stanley'),
    ('national-australia-bank--', 'National Australia Bank'),
    ('national-bank-of-egypt--', 'National Bank of Egypt'),
    ('nedbank-group--', 'Nedbank Group'),
    ('next--', 'Next'),
    ('nordea--', 'Nordea'),
    ('nubank--', 'Nubank'),
    ('old-mutual-ltd--', 'Old Mutual Limited'),
    ('oversea-chinese-banking-corp--', 'Oversea-Chinese Banking Corporation'),
    ('pnc-fin-servs--', 'PNC Financial Services'),
    ('pagseguro--', 'PagSeguro'),
    ('paypal--', 'PayPal'),
    ('pepper-money--', 'Pepper Money'),
    ('picpay--', 'PicPay'),
    ('pao-de-acucar--', 'Pão de Açúcar'),
    ('regions-fin--', 'Regions Financial Corporation'),
    ('remgro-ltd--', 'Remgro Limited'),
    ('resimac--', 'Resimac'),
    ('royal-bank-of-scotland--', 'Royal Bank of Scotland'),
    ('sanlam-ltd--', 'Sanlam Limited'),
    ('santander--', 'Santander'),
    ('siam-commercial-bank--', 'Siam Commercial Bank'),
    ('skandinaviska-enskilda-banken--', 'Skandinaviska Enskilda Banken'),
    ('societe-generale--', 'Société Générale'),
    ('standard-bank-group--', 'Standard Bank Group'),
    ('state-bank-of-india--', 'State Bank of India'),
    ('state-street--', 'State Street'),
    ('sumitomo-mitsui-fin-group--', 'Sumitomo Mitsui Financial Group'),
    ('suntrust-banks--', 'SunTrust Banks'),
    ('suncorp-group--', 'Suncorp Group'),
    ('svenska-handelsbanken--', 'Svenska Handelsbanken'),
    ('td-bank--', 'TD Bank'),
    ('bank-of-new-york-mellon--', 'The Bank of New York Mellon'),
    ('ticket--', 'Ticket'),
    ('us-bancorp--', 'U.S. Bancorp'),
    ('ubs--', 'UBS'),
    ('unicredit--', 'UniCredit'),
    ('united-bank-for-africa--', 'United Bank for Africa'),
    ('united-overseas-bank--', 'United Overseas Bank'),
    ('wells-fargo--', 'Wells Fargo'),
    ('westpac--', 'Westpac'),
    ('zenith-bank--', 'Zenith Bank'),
]

brands: list[tuple[str, str]] = [
    ('anz-rewards-visa--', 'ANZ Rewards Visa'),
    ('afriqard--', 'Afriqard'),
    ('airtel-money--', 'Airtel Money'),
    ('amazon-store-card--', 'Amazon Store Card'),
    ('amex--', 'American Express'),
    ('american-express--', 'American Express'),
    ('apple-card--', 'Apple Card'),
    ('bcard--', 'BC Card'),
    ('boc-cards--', 'BOC Cards'),
    ('bancontact--', 'Bancontact'),
    ('bank-of-america--', 'Bank of America'),
    ('bank-of-melbourne-amplify-visa--', 'Bank of Melbourne Amplify Visa'),
    ('bankcard--', 'Bankcard'),
    ('barclays-us--', 'Barclays US'),
    ('best-buy-credit-card--', 'Best Buy Credit Card'),
    ('ccb-cards--', 'CCB Cards'),
    ('citic-cards--', 'CITIC Cards'),
    ('cmb-cards--', 'CMB Cards'),
    ('capital-one--', 'Capital One'),
    ('carte-bancaire--', 'Carte Bancaire'),
    ('jpmorgan-chase--', 'Chase'),
    ('citibank--', 'Citibank'),
    ('citibank-rewards-visa--', 'Citibank Rewards Visa'),
    ('coles-mastercard--', 'Coles Mastercard'),
    ('commbank-awards-mastercard--', 'CommBank Awards Mastercard'),
    ('dankort--', 'Dankort'),
    ('diners-club--', 'Diners Club'),
    ('diners-africa--', 'Diners Club'),
    ('diners-australia--', 'Diners Club'),
    ('diners-club-international--', 'Diners Club International'),
    ('discover--', 'Discover'),
    ('eps-austria--', 'EPS Austria'),
    ('elo--', 'Elo'),
    ('equitel--', 'Equitel'),
    ('eurocard--', 'Eurocard'),
    ('forbrugsforeningskort--', 'Forbrugsforeningskort'),
    ('gcash--', 'GCash'),
    ('giropay--', 'Giropay'),
    ('hsbc-visa--', 'HSBC'),
    ('hipercard--', 'Hipercard'),
    ('home-depot-credit-card--', 'Home Depot Credit Card'),
    ('hyundai-card--', 'Hyundai Card'),
    ('icbc-cards--', 'ICBC Cards'),
    ('interswitch--', 'Interswitch'),
    ('jcb--', 'JCB'),
    ('kb-kookmin-card--', 'KB Kookmin Card'),
    ('kohls-credit-card--', "Kohl's Credit Card"),
    ('lotte-card--', 'Lotte Card'),
    ('lowes-credit-card--', "Lowe's Credit Card"),
    ('m-pesa--', 'M-Pesa'),
    ('mb-net--', 'MB Net'),
    ('macquarie-platinum-card--', 'Macquarie Platinum Card'),
    ('macy-s-credit-card--', "Macy's Credit Card"),
    ('maestro--', 'Maestro'),
    ('mastercard--', 'Mastercard'),
    ('multibanco--', 'Multibanco'),
    ('nab-rewards-visa--', 'NAB Rewards Visa'),
    ('nibss-instant-payments--', 'NIBSS Instant Payments'),
    ('navy-federal-credit-union--', 'Navy Federal Credit Union'),
    ('orange-money--', 'Orange Money'),
    ('payattitude--', 'PayAttitude'),
    ('paypal-credit--', 'PayPal Credit'),
    ('pesalink--', 'PesaLink'),
    ('postpay--', 'PostPay'),
    ('postepay--', 'PostePay'),
    ('qantas-american-express--', 'Qantas American Express'),
    ('rswitch--', 'RSwitch'),
    ('rupay--', 'RuPay'),
    ('sofort--', 'SOFORT'),
    ('shinhan-card--', 'Shinhan Card'),
    ('sirdirect--', 'SiR Direct'),
    ('st-george-amplify-visa--', 'St. George Amplify Visa'),
    ('synchrony-fin--', 'Synchrony Financial'),
    ('target-redcard--', 'Target RedCard'),
    ('tigo-pesa--', 'Tigo Pesa'),
    ('truemoney--', 'TrueMoney'),
    ('usaa--', 'USAA'),
    ('unionpay--', 'UnionPay'),
    ('vpay--', 'VPay'),
    ('verve--', 'Verve'),
    ('visa--', 'Visa'),
    ('walmart-capital-one--', 'Walmart Capital One'),
    ('wells-fargo--', 'Wells Fargo'),
    ('westpac-altitude-mastercard--', 'Westpac Altitude Mastercard'),
    ('woolworths-money--', 'Woolworths Money'),
    ('ziwapay--', 'Ziwapay'),
    ('eftpos--', 'eftpos'),
    ('ideal--', 'iDEAL'),
]

services: list[tuple[str, str]] = (
    [
        ('aws--', 'AWS'),
        ('adobe--', 'Adobe'),
        ('airbnb--', 'Airbnb'),
        ('al-azhar-u--', 'Al-Azhar University'),
        ('amazon--', 'Amazon'),
        ('prime-video--', 'Amazon Prime Video'),
        ('ambev--', 'Ambev'),
        ('americanas--', 'Americanas'),
        ('amil--', 'Amil'),
        ('anhanguera--', 'Anhanguera'),
        ('apple--', 'Apple'),
        ('assai--', 'Assaí Atacadista'),
        ('atacadão--', 'Atacadão'),
        ('atari--', 'Atari'),
        ('anu--', 'Australian National University'),
        ('b3--', 'B3 (Brasil Bolsa Balcão)'),
        ('bradesco--', 'Banco Bradesco'),
        ('banco-do-brasil--', 'Banco do Brasil'),
        ('blizzard--', 'Blizzard Entertainment'),
        ('booking--', 'Booking'),
        ('cea--', 'C&A'),
        ('cma--', 'CMA Vantagens'),
        ('cairo-u--', 'Cairo University'),
        ('caltech--', 'California Institute of Technology'),
        ('carrefour--', 'Carrefour Brasil'),
        ('cec--', 'Cec Materiais de Construção'),
        ('claro--', 'Claro Brasil'),
        ('columbia--', 'Columbia University'),
        ('cornell--', 'Cornell University'),
        ('deezer--', 'Deezer'),
        ('discord--', 'Discord'),
        ('disney-plus--', 'Disney+'),
        ('duke--', 'Duke University'),
        ('espm--', 'ESPM'),
        ('eth-zurich--', 'ETH Zurich'),
        ('epic-games--', 'Epic Games'),
        ('estacio--', 'Estácio'),
        ('extra--', 'Extra'),
        ('fgv--', 'FGV'),
        ('fia--', 'FIA Business School'),
        ('facebook--', 'Facebook'),
        ('fast-shop--', 'Fast Shop'),
        ('gatech--', 'Georgia Institute of Technology'),
        ('github--', 'Github'),
        ('glassdoor--', 'Glassdoor'),
        ('google--', 'Google'),
        ('gov-br--', 'Gov BR'),
        ('hapvida--', 'Hapvida'),
        ('harvard--', 'Harvard University'),
        ('havan--', 'Havan'),
        ('heidelberg--', 'Heidelberg University'),
        ('heroku--', 'Heroku'),
        ('ibmec--', 'IBMEC'),
        ('ime--', 'IME'),
        ('ita--', 'ITA'),
        ('ibovespa--', 'Ibovespa'),
        ('imperial-college--', 'Imperial College London'),
        ('indeed--', 'Indeed'),
        ('insper--', 'Insper'),
        ('instagram--', 'Instagram'),
        ('itau--', 'Itaú Unibanco'),
        ('jhu--', 'Johns Hopkins University'),
        ('ku-leuven--', 'KU Leuven'),
        ('kayak--', 'Kayak'),
        ('kcl--', "King's College London"),
        ('kwai--', 'Kwai'),
        ('kyoto-u--', 'Kyoto University'),
        ('lg--', 'LG'),
        ('leiden--', 'Leiden University'),
        ('leroy-merlin--', 'Leroy Merlin Brasil'),
        ('linkedin--', 'LinkedIn'),
        ('renner--', 'Lojas Renner'),
        ('lse--', 'London School of Economics and Political Science'),
        ('mit--', 'MIT'),
        ('magazine-luiza--', 'Magazine Luiza'),
        ('magalu--', 'Magazine Luiza'),
        ('marisa--', 'Marisa'),
        ('mercado-livre--', 'Mercado Livre'),
        ('motorola--', 'Motorola'),
        ('ntu-singapore--', 'Nanyang Technological University, Singapore'),
        ('national-u-singapore--', 'National University of Singapore'),
        ('natura--', 'Natura &Co'),
        ('netflix--', 'Netflix'),
        ('nyu--', 'New York University'),
        ('nintendo--', 'Nintendo'),
        ('northwestern--', 'Northwestern University'),
        ('notion--', 'Notion'),
        ('notredame-intermedica--', 'Notredame Intermédica'),
        ('nu-invest--', 'Nu Invest'),
        ('boticario--', 'O Boticário'),
        ('oi--', 'Oi'),
        ('osaka-u--', 'Osaka University'),
        ('outlook--', 'Outlook'),
        ('puc-rio--', 'PUC-Rio'),
        ('puc-sp--', 'PUC-SP'),
        ('peking-u--', 'Peking University'),
        ('petrobras--', 'Petrobras'),
        ('pinterest--', 'Pinterest'),
        ('playstation--', 'PlayStation'),
        ('polishop--', 'Polishop'),
        ('porto-seguro--', 'Porto Seguro'),
        ('prevent-senior--', 'Prevent Senior'),
        ('princeton--', 'Princeton University'),
        ('pao-de-acucar--', 'Pão de Açúcar'),
        ('reddit--', 'Reddit'),
        ('revelo--', 'Revelo'),
        ('riachuelo--', 'Riachuelo'),
        ('riot-games--', 'Riot Games'),
        ('shein--', 'SHEIN'),
        ('sams-club--', "Sam's Club Brasil"),
        ('samsung--', 'Samsung'),
        ('shopee--', 'Shopee'),
        ('skype--', 'Skype'),
        ('slack--', 'Slack'),
        ('spotify--', 'Spotify'),
        ('stanford--', 'Stanford University'),
        ('steam--', 'Steam'),
        ('stripe--', 'Stripe'),
        ('submarino--', 'Submarino'),
        ('sulamerica--', 'Sulamerica'),
        ('supercell--', 'Supercell'),
        ('tim--', 'TIM Brasil'),
        ('tum--', 'Technical University of Munich'),
        ('telhanorte--', 'Telhanorte'),
        ('ticket--', 'Ticket'),
        ('tiktok--', 'TikTok'),
        ('trello--', 'Trello'),
        ('trip-advisor--', 'Trip Advisor'),
        ('tsinghua--', 'Tsinghua University'),
        ('twitch--', 'Twitch'),
        ('twitter--', 'Twitter'),
        ('ufba--', 'UFBA'),
        ('ufc--', 'UFC'),
        ('ufmg--', 'UFMG'),
        ('ufpe--', 'UFPE'),
        ('ufpr--', 'UFPR'),
        ('ufrgs--', 'UFRGS'),
        ('ufrj--', 'UFRJ'),
        ('ufsc--', 'UFSC'),
        ('ufu--', 'UFU'),
        ('unesp--', 'UNESP'),
        ('unicamp--', 'UNICAMP'),
        ('unip--', 'UNIP'),
        ('usp--', 'USP'),
        ('unimed--', 'Unimed'),
        ('uninter--', 'Uninter'),
        ('anhembi-morumbi--', 'Universidade Anhembi Morumbi'),
        ('mackenzie--', 'Universidade Presbiteriana Mackenzie'),
        ('ucl--', 'University College London'),
        ('amsterdam-uva--', 'University of Amsterdam'),
        ('bristol--', 'University of Bristol'),
        ('uc-berkeley--', 'University of California, Berkeley'),
        ('ucla--', 'University of California, Los Angeles'),
        ('ucsd--', 'University of California, San Diego'),
        ('cambridge--', 'University of Cambridge'),
        ('uct--', 'University of Cape Town'),
        ('uchicago--', 'University of Chicago'),
        ('edinburgh--', 'University of Edinburgh'),
        ('glasgow--', 'University of Glasgow'),
        ('manchester--', 'University of Manchester'),
        ('u-melbourne--', 'University of Melbourne'),
        ('umich--', 'University of Michigan'),
        ('unsw--', 'University of New South Wales'),
        ('oxford--', 'University of Oxford'),
        ('upenn--', 'University of Pennsylvania'),
        ('uq--', 'University of Queensland'),
        ('u-sydney--', 'University of Sydney'),
        ('tokyo-u--', 'University of Tokyo'),
        ('warwick--', 'University of Warwick'),
        ('uwashington--', 'University of Washington'),
        ('wits--', 'University of the Witwatersrand'),
        ('utrecht--', 'Utrecht University'),
        ('vale--', 'Vale'),
        ('vercel--', 'Vercel'),
        ('via--', 'Via (Casas Bahia, Ponto Frio)'),
        ('vivo--', 'Vivo'),
        ('wargaming--', 'Wargaming'),
        ('wordpress--', 'Wordpress'),
        ('xbox--', 'Xbox'),
        ('yahoo--', 'Yahoo'),
        ('yale--', 'Yale University'),
        ('epfl--', 'École Polytechnique Fédérale de Lausanne'),
    ]
    + banks
    + brands
)


cards_banks: list[tuple[str, str]] = sorted(set(banks), key=lambda x: x[1])
cards_brands: list[tuple[str, str]] = sorted(set(brands), key=lambda x: x[1])
credentials_services: list[tuple[str, str]] = sorted(set(services), key=lambda x: x[1])
notes_types: list[tuple[str, str]] = sorted(set(notes), key=lambda x: x[1])


cards_banks.insert(0, ('other--', 'Other'))
cards_brands.insert(0, ('other--', 'Other'))
credentials_services.insert(0, ('other--', 'Other'))
notes_types.append(('oth', 'Other'))
