Table User { 
  ID integer [pk, unique, not null, increment, note: 'ID da tabela']
  first_name varchar(150) [not null, note: 'Nome do usuário']
  last_name varchar(150) [not null, note: 'Sobrenome do usuário']
  email varchar(120) [unique, not null, note: 'Email de acesso do usuário']
  password varchar(32) [not null, note: 'Hash SHA256 da senha inserida pelo usuário']

  Note: 'Usuários do sistema'
}

Table ActivationAccountToken {
  ID uuid [pk, unique, not null, note: 'ID da tabela']
  user integer [not null, note: 'Referência externa a um usuário da tabela User']
  value varchar(64) [not null, note: 'Valor do token de ativação de conta']
  used bool [default: false, not null, note: 'Define se o token já foi utilizado']
  created timestamp [not null, default: `now()`, note: 'Data de criação']

  Note: 'Tokens de ativação de usuários do sistema'
}


// REFERENCIES

Ref ActivationAccountToken_User: ActivationAccountToken.user > User.ID
