services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../SWARDEN:/app
    command: >
      bash -c "
      pip install django-extensions
      && uv run manage.py collectstatic --noinput
      && uv run manage.py migrate
      && uv run gunicorn CORE.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
