# Generated by Django 5.1 on 2024-10-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secret", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="card",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="logincredential",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="logincredential",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="securitynote",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="securitynote",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
