site_name: sWardenTheDocs
site_url: https://lucasgoncsilva.github.io/swarden/
repo_url: https://github.com/LucasGoncSilva/swarden
repo_name: LucasGoncSilva/sWarden
edit_uri: edit/main/documentation/
theme:
  name: material
  language: en
  favicon: img/logo.svg
  logo: img/logo.svg
  font:
    text: Ubuntu
  icon:
    tag:
      homepage: fontawesome/solid/house
      index: fontawesome/solid/file
      overview: fontawesome/solid/binoculars
      test: fontawesome/solid/flask-vial
      infra: fontawesome/solid/server
      doc: fontawesome/solid/book
      legal: fontawesome/solid/scale-unbalanced
      user: fontawesome/solid/user
      API: fontawesome/solid/gears
      browser: fontawesome/solid/desktop
    next: fontawesome/solid/arrow-right
    previous: fontawesome/solid/arrow-left
    top: fontawesome/solid/arrow-up
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/fire-flame-simple
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/xmark
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/bug
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Light/Dark Mode
    primary: indigo
    accent: indigo
  - scheme: slate
    toggle:
      icon: material/brightness-3
      name: Light/Dark Mode
    primary: indigo
    accent: indigo
  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.top
  - header.autohide
  - navigation.footer
  - content.action.view
  - content.action.edit
  - announce.dismiss
  - content.tabs.link
markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
    pygments_lang_class: true
    auto_title: true
    linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- admonition
- pymdownx.details
- attr_list
- md_in_html
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.arithmatex:
    generic: true
- def_list
- pymdownx.tasklist:
    custom_checkbox: true
plugins:
- search
- tags
- git-revision-date-localized:
    enable_creation_date: true
    type: datetime
    enabled: true
    fallback_to_build_date: true
    locale: en
extra:
  tags:
    Homepage: homepage
    Index: index
    Overview: overview
    Teste: test
    Infra: infra
    Documentation: doc
    Legal: legal
    "Usu\xE1rio": user
    API: API
    Browser: browser
  status:
    new: New!
copyright: Copyright 2025 LucasGonc
nav:
- Homepage: index.md
- Code of Conduct: CODE_OF_CONDUCT.md
- Contributing: CONTRIBUTING.md
- Security: SECURITY.md
- Support: SUPPORT.md
- ToDo: TODO.md
- Changelog: CHANGELOG.md
- Codebase:
  - SWARDEN:
    - manage.py: Codebase/SWARDEN/manage.py.md
    - utils.py: Codebase/SWARDEN/utils.py.md
    - crypt.py: Codebase/SWARDEN/crypt.py.md
    - home:
      - apps.py: Codebase/SWARDEN/home/apps.py.md
      - urls.py: Codebase/SWARDEN/home/urls.py.md
      - __init__.py: Codebase/SWARDEN/home/__init__.py.md
      - views.py: Codebase/SWARDEN/home/views.py.md
      - management:
        - commands:
          - testwithcoverage.py: Codebase/SWARDEN/home/management/commands/testwithcoverage.py.md
          - __init__.py: Codebase/SWARDEN/home/management/commands/__init__.py.md
      - tests:
        - test_views.py: Codebase/SWARDEN/home/tests/test_views.py.md
        - __init__.py: Codebase/SWARDEN/home/tests/__init__.py.md
    - account:
      - admin.py: Codebase/SWARDEN/account/admin.py.md
      - apps.py: Codebase/SWARDEN/account/apps.py.md
      - models.py: Codebase/SWARDEN/account/models.py.md
      - urls.py: Codebase/SWARDEN/account/urls.py.md
      - __init__.py: Codebase/SWARDEN/account/__init__.py.md
      - views.py: Codebase/SWARDEN/account/views.py.md
      - forms.py: Codebase/SWARDEN/account/forms.py.md
      - management:
        - commands:
          - populateuser.py: Codebase/SWARDEN/account/management/commands/populateuser.py.md
          - __init__.py: Codebase/SWARDEN/account/management/commands/__init__.py.md
      - migrations:
        - 0001_initial.py: Codebase/SWARDEN/account/migrations/0001_initial.py.md
        - __init__.py: Codebase/SWARDEN/account/migrations/__init__.py.md
      - tests:
        - test_models.py: Codebase/SWARDEN/account/tests/test_models.py.md
        - test_views.py: Codebase/SWARDEN/account/tests/test_views.py.md
        - __init__.py: Codebase/SWARDEN/account/tests/__init__.py.md
    - CORE:
      - wsgi.py: Codebase/SWARDEN/CORE/wsgi.py.md
      - asgi.py: Codebase/SWARDEN/CORE/asgi.py.md
      - urls.py: Codebase/SWARDEN/CORE/urls.py.md
      - __init__.py: Codebase/SWARDEN/CORE/__init__.py.md
      - settings:
        - deploy.py: Codebase/SWARDEN/CORE/settings/deploy.py.md
        - dev.py: Codebase/SWARDEN/CORE/settings/dev.py.md
        - base.py: Codebase/SWARDEN/CORE/settings/base.py.md
    - general:
      - apps.py: Codebase/SWARDEN/general/apps.py.md
      - urls.py: Codebase/SWARDEN/general/urls.py.md
      - __init__.py: Codebase/SWARDEN/general/__init__.py.md
      - views.py: Codebase/SWARDEN/general/views.py.md
      - tests:
        - test_views.py: Codebase/SWARDEN/general/tests/test_views.py.md
        - __init__.py: Codebase/SWARDEN/general/tests/__init__.py.md
    - secret:
      - admin.py: Codebase/SWARDEN/secret/admin.py.md
      - apps.py: Codebase/SWARDEN/secret/apps.py.md
      - choices.py: Codebase/SWARDEN/secret/choices.py.md
      - urls.py: Codebase/SWARDEN/secret/urls.py.md
      - __init__.py: Codebase/SWARDEN/secret/__init__.py.md
      - views.py: Codebase/SWARDEN/secret/views.py.md
      - month:
        - widgets.py: Codebase/SWARDEN/secret/month/widgets.py.md
        - models.py: Codebase/SWARDEN/secret/month/models.py.md
        - util.py: Codebase/SWARDEN/secret/month/util.py.md
        - __init__.py: Codebase/SWARDEN/secret/month/__init__.py.md
        - forms.py: Codebase/SWARDEN/secret/month/forms.py.md
      - management:
        - commands:
          - populatesecret.py: Codebase/SWARDEN/secret/management/commands/populatesecret.py.md
          - __init__.py: Codebase/SWARDEN/secret/management/commands/__init__.py.md
      - migrations:
        - 0001_initial.py: Codebase/SWARDEN/secret/migrations/0001_initial.py.md
        - __init__.py: Codebase/SWARDEN/secret/migrations/__init__.py.md
      - models:
        - logincredential.py: Codebase/SWARDEN/secret/models/logincredential.py.md
        - securitynotes.py: Codebase/SWARDEN/secret/models/securitynotes.py.md
        - __init__.py: Codebase/SWARDEN/secret/models/__init__.py.md
        - card.py: Codebase/SWARDEN/secret/models/card.py.md
      - tests:
        - test_xor.py: Codebase/SWARDEN/secret/tests/test_xor.py.md
        - test_models.py: Codebase/SWARDEN/secret/tests/test_models.py.md
        - test_views.py: Codebase/SWARDEN/secret/tests/test_views.py.md
        - __init__.py: Codebase/SWARDEN/secret/tests/__init__.py.md
    - mail:
      - apps.py: Codebase/SWARDEN/mail/apps.py.md
      - models.py: Codebase/SWARDEN/mail/models.py.md
      - urls.py: Codebase/SWARDEN/mail/urls.py.md
      - __init__.py: Codebase/SWARDEN/mail/__init__.py.md
      - views.py: Codebase/SWARDEN/mail/views.py.md
      - migrations:
        - 0001_initial.py: Codebase/SWARDEN/mail/migrations/0001_initial.py.md
        - __init__.py: Codebase/SWARDEN/mail/migrations/__init__.py.md
      - tests:
        - test_views.py: Codebase/SWARDEN/mail/tests/test_views.py.md
        - __init__.py: Codebase/SWARDEN/mail/tests/__init__.py.md
    - err:
      - apps.py: Codebase/SWARDEN/err/apps.py.md
      - urls.py: Codebase/SWARDEN/err/urls.py.md
      - __init__.py: Codebase/SWARDEN/err/__init__.py.md
      - views.py: Codebase/SWARDEN/err/views.py.md
      - tests:
        - test_views.py: Codebase/SWARDEN/err/tests/test_views.py.md
        - __init__.py: Codebase/SWARDEN/err/tests/__init__.py.md
    - plans:
      - tests.py: Codebase/SWARDEN/plans/tests.py.md
      - admin.py: Codebase/SWARDEN/plans/admin.py.md
      - apps.py: Codebase/SWARDEN/plans/apps.py.md
      - models.py: Codebase/SWARDEN/plans/models.py.md
      - urls.py: Codebase/SWARDEN/plans/urls.py.md
      - __init__.py: Codebase/SWARDEN/plans/__init__.py.md
      - views.py: Codebase/SWARDEN/plans/views.py.md
      - migrations:
        - __init__.py: Codebase/SWARDEN/plans/migrations/__init__.py.md
